

// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbfk7tOz3fhlOLnlkWryPuUAny6tN2Zhk',
    appId: '1:951766696602:web:94cfdc66714878ce41d523',
    messagingSenderId: '951766696602',
    projectId: 'construction-monitoring-iot',
    authDomain: 'construction-monitoring-iot.firebaseapp.com',
    databaseURL: 'https://construction-monitoring-iot-default-rtdb.firebaseio.com',
    storageBucket: 'construction-monitoring-iot.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-ufRlaSXBZR4uMH8Hz4jzIhf_ITapZCs',
    appId: '1:951766696602:android:ea308a0b37708f0441d523',
    messagingSenderId: '951766696602',
    projectId: 'construction-monitoring-iot',
    databaseURL: 'https://construction-monitoring-iot-default-rtdb.firebaseio.com',
    storageBucket: 'construction-monitoring-iot.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCT_BMvlQbtG69u2uctHNozyULApgf_M1g',
    appId: '1:951766696602:ios:72364e98ae6ed3af41d523',
    messagingSenderId: '951766696602',
    projectId: 'construction-monitoring-iot',
    databaseURL: 'https://construction-monitoring-iot-default-rtdb.firebaseio.com',
    storageBucket: 'construction-monitoring-iot.firebasestorage.app',
    iosBundleId: 'com.example.structuralAlertSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCT_BMvlQbtG69u2uctHNozyULApgf_M1g',
    appId: '1:951766696602:ios:72364e98ae6ed3af41d523',
    messagingSenderId: '951766696602',
    projectId: 'construction-monitoring-iot',
    databaseURL: 'https://construction-monitoring-iot-default-rtdb.firebaseio.com',
    storageBucket: 'construction-monitoring-iot.firebasestorage.app',
    iosBundleId: 'com.example.structuralAlertSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbfk7tOz3fhlOLnlkWryPuUAny6tN2Zhk',
    appId: '1:951766696602:web:0dd02573df4817a641d523',
    messagingSenderId: '951766696602',
    projectId: 'construction-monitoring-iot',
    authDomain: 'construction-monitoring-iot.firebaseapp.com',
    databaseURL: 'https://construction-monitoring-iot-default-rtdb.firebaseio.com',
    storageBucket: 'construction-monitoring-iot.firebasestorage.app',
  );
}
